### ISSUE TITLE
Update Fortnite authentication

### ISSUE THREAD

**Issue by ecly** [Hanspagh/buddy_matching#151]
A couple of days ago Fortnite updated their authentication for the API.

See this commit for changes:
https://github.com/Terbau/fortnitepy/commit/24db7763c3bd94374712d3abbbbb3c27ab81df91 

or the discussion here:
https://github.com/qlaffont/fortnite-api/issues/192

**Comment by ecly** [comment]
Here is another example of the new login flow:
https://gist.github.com/iXyles/ec40cb40a2a186425ec6bfb9dcc2ddda

**Comment by iXyles** [comment]
Information: The commit changes for fortnitepy is a bad way of doing it. Terbau only did it mean while I was working/figuring out how to use the new auth flow. He has changed to the same auth flow as you linked above which was made in C#

Here is another example of it but in Py by Terbau:
https://gist.github.com/Terbau/9a07849fb30c0232af730265c327e27c

**Comment by PomegranateApps** [comment]
Can someone confirm if any of these solutions are working for them? I tried all of these but I'm still not able to get authenticated. I can't seem to login at the "id/api/login" endpoint.

**Comment by iXyles** [comment]
The given example of the C# posted by ecly which is made by me, or the python solution from Terbau works. I even have it implemented in my Node.JS Project "fortnite-basic-api" if you wish to take a look. But otherwise you can try the C# code and you'll see it works.

**Comment by PomegranateApps** [comment]
Thank you for this additional information. I tried the fortnite-basic-api and it does work but I'm unable to replicate the request for the exchange code. I'm working on a limited environment and the fortnite-basic-api requires a lot of modules.

This is my request for the exchange code. It looks identical to the fortnite-basic-api.
```
{ hostname: 'www.epicgames.com',
  path: '/id/api/exchange',
  method: 'GET',
  json: true,
  headers:
   { 'Content-Type': 'application/json',
     'x-xsrf-token': '...' }
}
```

I'm getting this error after I make this request.
```
{ errorCode: 'errors.com.epicgames.unauthorized',
  message: 'You are not authenticated. Please authenticate.' }
```

I'm able to login successfully using the login endpoint. Is there another step I'm supposed to do before making this request?

**Comment by iXyles** [comment]
As demostrate in the C# example, we also need to pass on the cookie to the other two requests.

This is done behind the scene in my node library in the requester :)

So, csrf > cookie& xsrf (login) > cookie & xsrf (Exchange)

**Comment by PomegranateApps** [comment]
Ok, thank for letting me know! I really appreciate the information. This updated login flow is much more complicated than the previous one.

**Comment by ecly** [comment]
Thanks for the information guys - I'll presumably update our [AccessServer](https://github.com/BuddyGG/buddy_matching/blob/development/apps/fortnite_api/lib/fortnite_api/access_server.ex) for this new flow within a few days, if anyone cares for an Elixir implementation.

**Comment by psykodead** [comment]
I dont care of comments deleted (again and again) or of your answer or of u anyway, Check my twiter 4 c GLITCHS in Epic fails games AND GLITCH THAT REST 10 YEARS AFTHER THE GAME WAS BUILD (starcraft2) what will happen to UT4 the Epic fail twitter.com/psykodead hxxps://twitter.com/psykodead twitter:com/psykodead
